### ISSUE TITLE
Missing date and timezone

### ISSUE THREAD

**Issue by IRuFFeYI** [IQNeoXen/drachenlord-discord-bot#1]
Grüß Gott zusammen  (@IQNeoXen),

es gibt ein großes Problem. Bei der Übersicht der Flüge fehlen sowohl die Zeitzone als auch das jeweilige Datum.

Bitte schnellstmöglich fixen. So kann man nicht arbeiten.

Mit besten Grüßen

**Comment by IQNeoXen** [comment]
Halloservusgriaßdi @IRuFFeYI,

verwenden Sie hierfür bitte dieses Repo: https://git.neoxen.de/frank/bumsung-der-amis

drottl.

mfg
