### ISSUE TITLE
Traceback Error in Docker unter Windows

### ISSUE THREAD

**Issue by ninjasan420** [IQNeoXen/drachenlord-discord-bot#2]
Moin, bekomme beim starten folgenden Fehler:

drache-drachenlord-1  | Traceback (most recent call last):
drache-drachenlord-1  |   File "/app/./main.py", line 29, in <module>
drache-drachenlord-1  |     client.timer_manager = timers.TimerManager(client)
drache-drachenlord-1  |   File "/usr/local/lib/python3.10/site-packages/discord/ext/timers/timers.py", line 132, in __init__
drache-drachenlord-1  |     self.__timers = ListBasedQueue(loop=bot.loop)
drache-drachenlord-1  |   File "/usr/local/lib/python3.10/asyncio/queues.py", line 33, in __init__
drache-drachenlord-1  |     super().__init__(loop=loop)
drache-drachenlord-1  |   File "/usr/local/lib/python3.10/asyncio/mixins.py", line 17, in __init__
drache-drachenlord-1  |     raise TypeError(
drache-drachenlord-1  | TypeError: As of 3.10, the *loop* parameter was removed from ListBasedQueue() since it is no longer necessary

Hast du ne Idee was ich falsch mache? :)
LG und danke!

**Comment by h45h74x** [comment]
Hi, 

das Problem tritt auf, weil in der Dockerfile keine Version für `discord.py` spezifiziert wurde - es wird daher immer die neueste Version genutzt. Da für die aktuelle Python-Version der bisherige Code angepasst werden müsste, ist es am einfachsten, eine alte Version von `discord.py` zu verwenden.

Um beispielsweise die Version `3.9.4` zu verwenden, muss der Inhalt der Datei `Dockerfile` wie folgt aussehen:
```
FROM gorialis/discord.py:3.9.4-minimal

COPY src/ /app
WORKDIR /app

RUN pip install -r requirements.txt

CMD [ "python", "./main.py" ]
```

Sobald die Datei überschrieben wurde, kann man den Docker-Container mit `docker-compose build` neu bauen und, wie in der Readme.md, mit `docker-compose up` ausführen.

Viel Spaß :D

**Comment by ninjasan420** [comment]
Meddl du Kaschber,

hat wunderbar geklappt, merci vielmol! (°°,)

E schees Wocheend, gell?
